### ISSUE TITLE
请问下，每次续期都要运行两次才行

### ISSUE THREAD

**Issue by binhe-cpu** [SAOJSM/EU_CHICK_EXTEND_CHT#2]
******************************
[EUserv] 正在续期第 1 个帐号 XXXX@XXX.XXX
[Captcha Solver] 进行验证码识别...
[Captcha Solver] You are using your own apikey.
[Captcha Solver] 识别的验证码是: Aoo9EB
[Captcha Solver] current date 2022-09-13 api usage count: 1
[Captcha Solver] 验证通过
[EUserv] 检测到第 1 个帐号有 0 台 VPS，正在尝试续期
[EUserv] ALL Work Done! Enjoy~

******************************
[EUserv] 正在续期第 1 个帐号 XXXX@XXX.XXX
[Email] pin code:885816
[EUserv] 检测到第 1 个帐号有 1 台 VPS，正在尝试续期
[EUserv] Send pin code to XXXX@XXX.XXX Time: 2022-09-13 07:06:25
[EUserv] A PIN has been sent to your email address
[Email] pin code:543414
[EUserv] ServerID: 358534 德鸡续期成功!
[EUserv] ALL Work Done! Enjoy~

**Comment by insoxin** [comment]
EUserv续期日志

******************************
[EUserv] 正在续期第 1 个账号
[Captcha Solver] 进行验证码识别...
[Captcha Solver] You are using your own apikey.
[Captcha Solver] 识别的验证码是: 3
[Captcha Solver] current date 2022-11-23 api usage count: 1
[Captcha Solver] 验证通过
[EUserv] 检测到第 1 个账号有 0 台 VPS，正在尝试续期
[EUserv] ALL Work Done! Enjoy~



我也是,你解决了吗 @binhe-cpu @SAOJSM

**Comment by SAOJSM** [comment]
網站抽風，改下crontab時間就好
